swagger: "2.0"
info:
  title: Image Viewer Service
  description: HTTP service for viewing image files hosted on S3
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /folders:
    get:
      tags:
      - image-viewer
      summary: folders image-viewer
      operationId: image-viewer#folders
      produces:
      - application/json
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Aliquam vitae eos possimus alias.
      schemes:
      - http
  /images:
    get:
      tags:
      - image-viewer
      summary: images image-viewer
      operationId: image-viewer#images
      produces:
      - application/json
      parameters:
      - name: folder
        in: query
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/ImageResponse'
      schemes:
      - http
definitions:
  ImageResponse:
    title: ImageResponse
    type: object
    properties:
      name:
        type: string
        description: name
        example: Est est deserunt eos.
      original_url:
        type: string
        description: signed original image url
        example: Minus veritatis nobis necessitatibus sint adipisci.
      thumbnail_url:
        type: string
        description: signed thumbnail image url
        example: Dolores illum nihil aliquid ipsa blanditiis.
    example:
      name: Esse et ut.
      original_url: Iusto corporis quia quos voluptatem eos minus.
      thumbnail_url: Unde quo sed corporis.
